---
- name: Wait for ssh connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 120
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local

- name: Install python3, docker, docker-compose
  hosts: all
  become: true
  vars:
    docker_compose_dir: /usr/local/lib/docker/cli-plugins
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - python3
          - docker
        update_cache: true
        state: present
    - name: Create directory for docker compose
      file:
        path: "{{ docker_compose_dir }}"
        state: directory
        recurse: true
    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-{{ lookup('pipe', 'uname -s') }}-{{ lookup('pipe', 'uname -m') }}
        dest: "{{ docker_compose_dir }}/docker-compose"
        mode: +x
    - name: Ensure docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose


- name: Create new linux user
  hosts: all
  become: true
  vars_files:
    - project-vars
  tasks:
    - name: Create new linux user
      ansible.builtin.user:
        name: "{{ linux_user }}"
        groups: adm,docker


- name: Start docker containers
  hosts: all
  become: true
  become_user: "{{ linux_user }}"
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: "{{ local_compose_file }}"
        dest: "/home/{{ linux_user }}/docker-compose.yaml"
    - name: Docker login
      vars:
        ansible_python_interpreter: /usr/bin/python
      community.docker.docker_login:
        username: "{{ docker_login }}"
        password: "{{ docker_password }}"
    - name: Start container from compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ linux_user }}"
