---
- name: Install python3, docker, dokcer-compose
  hosts: docker_server
  become: true
  tasks:
    - name: Make sure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: true
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-{{lookup('pipe', 'uname -s')}}-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

- name: Add ec2-user to docker group
  hosts: docker_server
  become: true
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
    - name: Reconnect to server session
      meta: reset_connection

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: Pull redis
      command: docker pull redis
      