---
- name: Install node and npm
  hosts: 134.122.71.113
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new user for the node app
  hosts: 134.122.71.113
  vars_files:
    - project-vars
  tasks:
    - name: Create linux user
      user:
        name: "{{linux_name}}"
        comment: armen admin
        group: admin

- name: Deploy nodejs app
  hosts: 134.122.71.113
  become: True
  become_user: "{{linux_name}}"
  vars_files:
    - project-vars
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: "{{location}}/react-nodejs-example-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      npm:
        path: "{{user_home_dir}}/package"
    - name: Start the application
      command:
        chdir: "{{user_home_dir}}/package"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}